### PR TITLE
Improvements on tests

### PR DESCRIPTION
**Pull request by dorianneto**
This PR contains:

- Tests to the "containsCaseless" method from class Str
- Builder class to help the tests
- Some comments in validator file methods

I forgot to describe the methods on comments. I'm sorry for this :/

### CODE REVIEW

**Comment by dorianneto** [comment]
Do you can rebuilding the project, please? The failed of Travis it's so weird :S

**Comment by arandilopez** [comment]
@dorianneto this is the output for your test

```
PHPUnit 4.8.35 by Sebastian Bergmann and contributors.


....EF........F.......


Time: 178 ms, Memory: 7.75MB


There was 1 error:


1) LaravelProfaneTests\ProfaneValidatorTest::test_can_validate_a_word_with_numbers

Undefined offset: 1


/home/travis/build/arandilopez/laravel-profane/tests/ProfaneValidatorBuilder.php:35

/home/travis/build/arandilopez/laravel-profane/tests/ProfaneValidatorTest.php:62


--


There were 2 failures:


1) LaravelProfaneTests\ProfaneValidatorTest::test_can_validate_a_text

Failed asserting that true is false.


/home/travis/build/arandilopez/laravel-profane/tests/ProfaneValidatorTest.php:69


2) LaravelProfaneTests\ProfaneValidatorTest::test_can_validate_a_text_in_greek

Failed asserting that true is false.


/home/travis/build/arandilopez/laravel-profane/tests/ProfaneValidatorTest.php:155


FAILURES!

Tests: 22, Assertions: 22, Errors: 1, Failures: 2.

```
Fails when runs on php 5.6

```json
{
  "language": "php",
  "php": "5.6",
  "install": [
    "composer self-update",
    "composer install"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```
I would like to support Laravel >= 5.2, it requires at least `php >= 5.6`, but if your feature it's not compatible maybe we need to remove that php 5.6 support and only point to laravel >= 5.5. Obviously re-tagging this package.

**Comment by dorianneto** [comment]
@arandilopez It will not be necessary because was a stupid error commited by me :P

In the Builder class, specifically on validate method, I setted the same method parameter name for the list() method variable. I'm sorry for this :/

Let's continuos make support to Laravel >= 5.2 because there are many projects that use yet.

**Comment by arandilopez** [comment]
@dorianneto I'm gonna merge it

**Comment by arandilopez** [comment]
I love that Builder. 

❤️ thanks

**Pull request merged**
