### PR TITLE
Simple typos

### PR DESCRIPTION
**Pull request by brunorsantos**

### CODE REVIEW

**Review by arandilopez — CHANGES_REQUESTED** [review]
Thanks, but we only need the word without accents. There is a method that clean accents before comparing words

**Comment by brunorsantos** [comment]
The words with accents already were in the pt-br file before.
I removed all the accents, can you verify now  @arandilopez ?
Thanks

**Review by arandilopez — APPROVED** [review]
Yeap, thank you.

**Comment by arandilopez** [comment]
Many languages uses different kind of accents, thats why some help us to ~remove~ replace accents form incoming input in validation

**Pull request merged**
