### PR TITLE
support laravel 6 and 7

### PR DESCRIPTION
**Pull request by okaufmann**
I've added support for Laravel 6 and 7. It works in a Laravel 7 I'm currently working on but did not test any further tough.

As composer.lock is not recommended in packages I added tests using prefer-lowest for installing packages in tests.

### CODE REVIEW

**Comment by arandilopez** [comment]
Excellent! Thank you so much @okaufmann :beers:

**Comment by okaufmann** [comment]
welcome

**Comment by okaufmann** [comment]
Would you mind to create a new release containing this pr 😊?

**Comment by arandilopez** [comment]
Sure

**Comment by okaufmann** [comment]
Thank you

**Pull request merged**
